# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verbs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_past', models.CharField(max_length=32)),
                ('simple_past_correct', models.BooleanField()),
                ('past_participle', models.CharField(max_length=32)),
                ('past_participle_correct', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Verb')),
            ],
        ),
    ]
