# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='infinitive',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
