# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 11:24
from __future__ import unicode_literals

import apps.verbs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_auto_20160121_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='infinitive',
            field=apps.verbs.models.LowerChartFiled(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_participle',
            field=apps.verbs.models.LowerChartFiled(max_length=32),
        ),
        migrations.AlterField(
            model_name='verb',
            name='simple_past',
            field=apps.verbs.models.LowerChartFiled(max_length=32),
        ),
    ]
